import type { AIAnalysisResult } from "@/lib/validations/ai";

export const renderEmailTemplate = (data: AIAnalysisResult): string => {
  const findingsList = data.key_findings
    .map((finding) => `<li style="margin-bottom: 8px;">${finding}</li>`)
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Monthly Analysis Report</title>
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background-color: #f9fafb; margin: 0; padding: 20px;">
  <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
    
    <!-- Header -->
    <div style="background-color: #ffffff; padding: 24px; border-bottom: 1px solid #e5e7eb;">
      <h1 style="margin: 0; font-size: 24px; font-weight: 700; color: #111827;">Monthly Analysis Report</h1>
    </div>

    <!-- Content -->
    <div style="padding: 24px;">
      
      <!-- Executive Summary -->
      <div style="margin-bottom: 24px;">
        <h2 style="margin: 0 0 12px 0; font-size: 18px; font-weight: 600; color: #111827;">Executive Summary</h2>
        <p style="margin: 0; color: #4b5563;">${data.summary}</p>
      </div>

      <!-- Key Findings -->
      <div style="margin-bottom: 24px;">
        <h2 style="margin: 0 0 12px 0; font-size: 18px; font-weight: 600; color: #111827;">Key Findings</h2>
        <ul style="margin: 0; padding-left: 20px; color: #4b5563;">
          ${findingsList}
        </ul>
      </div>

      <!-- Top Page -->
      <div style="margin-bottom: 24px;">
        <h2 style="margin: 0 0 12px 0; font-size: 18px; font-weight: 600; color: #111827;">Top Performing Page</h2>
        <p style="margin: 0; font-weight: 500; color: #2563eb;">${data.top_performing_page}</p>
      </div>

      <!-- Strategic Recommendation -->
      <div style="background-color: #eff6ff; border-left: 4px solid #3b82f6; padding: 16px; border-radius: 4px;">
        <h2 style="margin: 0 0 8px 0; font-size: 16px; font-weight: 600; color: #1e40af;">Strategic Recommendation</h2>
        <p style="margin: 0; color: #1e3a8a;">${data.strategic_recommendation}</p>
      </div>

    </div>

    <!-- Footer -->
    <div style="background-color: #f9fafb; padding: 16px; text-align: center; border-top: 1px solid #e5e7eb;">
      <p style="margin: 0; font-size: 12px; color: #6b7280;">Generated by DataGist</p>
    </div>

  </div>
</body>
</html>
  `.trim();
};
